config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'profiles', to: 'users/registrations#new_profile'
    post 'profiles', to: 'users/registrations#create_profile'
  end
  root 'home#index'
  resources :groups, only: [:new, :create, :edit, :update]
  resources :practices, only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many        :members
  has_many        :users, through: :members
  # has_many        :practices
  validates       :name, presence: true
  mount_uploader  :group_avatar, GroupAvatarUploader
end

app/models/job.rb
class Job < ActiveHash::Base
  self.data = [
  {id: 1, name: '社会人'}, {id: 2, name: '大学生'}, {id: 3, name: '高校生'},{id: 4, name: '中学生'},{id: 5, name: '小学生以下'},{id: 6, name: 'その他'}
  ]
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user, dependent: :destroy
  belongs_to :practice, dependent: :destroy
end

app/models/practice.rb
class Practice < ApplicationRecord
  has_many :practice_members
  has_many :users, through: :practice_members, dependent: :destroy
  has_many :participants, dependent: :destroy
  # belongs_to :group
  belongs_to :shuttle
  validates :name, :shuttle_id, :manager_id, presence: :true
end

app/models/practice_member.rb
class PracticeMember < ApplicationRecord
  belongs_to :user
  belongs_to :practice
end

app/models/practice_time.rb
class PracticeTime < ActiveHash::Base
  self.data = [
  {id: 1, name: '週4回以上'}, {id: 2, name: '週3〜4回'}, {id: 3, name: '週2〜3回'},{id: 4, name: '週1〜2回'},{id: 5, name: '月数回'},{id: 6, name: '年数回'},{id: 7, name: 'その他'}
  ]
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '北海道' }, { id: 2, name: '青森県' }, { id: 3, name: '岩手県' },
    { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' }, { id: 6, name: '山形県' },
    { id: 7, name: '福島県' }, { id: 8, name: '茨城県' }, { id: 9, name: '栃木県' },
    { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' }, { id: 12, name: '千葉県' },
    { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' }, { id: 15, name: '新潟県' },
    { id: 16, name: '富山県' }, { id: 17, name: '石川県' }, { id: 18, name: '福井県' },
    { id: 19, name: '山梨県' }, { id: 20, name: '長野県' }, { id: 21, name: '岐阜県' },
    { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' }, { id: 24, name: '三重県' },
    { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' }, { id: 27, name: '大阪府' },
    { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' }, { id: 30, name: '和歌山県' },
    { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' }, { id: 33, name: '岡山県' },
    { id: 34, name: '広島県' }, { id: 35, name: '山口県' }, { id: 36, name: '徳島県' },
    { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' }, { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' }, { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' }, { id: 44, name: '大分県' }, { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }
]
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to  :user, optional: true
  validates   :old, :job, :experience, :phonenumber, :practice_time, presence: true
  mount_uploader :avatar, AvatarUploader
end

app/models/shuttle.rb
class Shuttle < ApplicationRecord
  has_many :practices
  has_ancestry
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
  {id: 1, name: '○' }, {id: 2, name: '△' }, {id: 3, name: '×' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # :validatableは使用しないため削除
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one   :profile
  has_many  :members
  has_many  :practice_members
  has_many  :groups, through: :members, dependent: :destroy
  has_many  :practices, through: :practice_members, dependent: :destroy
  has_many  :messages, dependent: :destroy
  has_many  :participants, dependent: :destroy
  validates :nickname, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  # def index
  #   # cunnrent_userを含むgroup==current_user.idを含むgroupを取得する
  #   # @my_groups = Group.where('user_id like ?','current_user.id')
  #   @my_groups = current_user.groups

  # end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループ登録が完了しました"
    else
      flash.now[:alert] = "登録エラー。再度登録をしてください"
      render :new
    end
    
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: "グループを更新しました"
    else
      flash.now[:alert] = "更新エラー"
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :detail, :group_avatar, { user_ids: [] } )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @datas = Profile.all

    if user_signed_in?
      @my_groups = current_user.groups
    else
      @groups = Group.first(4)
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/with_error_form_builder.rb
class WithErrorFormBuilder < ActionView::Helpers::FormBuilder
  # エラーメッセージオブジェクトが格納されていたらエラーエッセージを表示するli要素を含んだ、ulを作成する
  def pick_errors(attribute)
    return nil if @object.nil? || (messages = @object.errors.messages[attribute]).nil?

    lis = messages.collect do |message|
      %(<li class="error__message">#{@object.errors.full_message(attribute, message)}</li>)
    end.join

    %(<ul class="error">#{lis}</ul>).html_safe
  end

  # 既存のフォールビルダーに対し、エラーメッセージの有無により、通常通りのヘルパーメソッドが、pick_errorsの呼び出しを加えたメソッドにする 
  def text_field(attribute, options = {})
    return super if options[:no_errors]

    super + pick_errors(attribute)
  end

  def email_field(attribute, options = {})
    return super if options[:no_errors]

    super + pick_errors(attribute)
  end

  def password_field(attribute, options = {})
    return super if options[:no_errors]

    super + pick_errors(attribute)
  end

  def telephone_field(attribute, options = {})
    return super if options[:no_errors]

    super + pick_errors(attribute)
  end

  def date_select(attribute, options = {})
    return super if options[:no_errors]

    super + pick_errors(attribute)
  end

  def collection_select(attribute, select, key, value, options = {}, include = {})
    return super if options[:no_errors]

    super + pick_errors(attribute)
  end

  def fields_for(attribute, options = {})
    return super if options[:no_errors]

    super + pick_errors(attribute)
  end

  def number_field(attribute, options = {})
    return super if options[:no_errors]

    super + pick_errors(attribute)
  end

  def text_area(attribute, options = {})
    return super if options[:no_errors]

    super + pick_errors(attribute)
  end

end

app/views/layouts/_notification.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Badsuru
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'flash', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shared/_footer.html.haml
.main-footer
  .main-footer__icon-img
    = image_tag '/images/footer-icon.png', alt: 'フッターアイコン',class: 'footer-icon__img'
  
  .main-footer__anouncement
    = link_to 'よくある質問', root_path, class: "main-footer__anouncement__link--first"
    = link_to '運営会社について', root_path, class: "main-footer__anouncement__link"
    = link_to 'お問い合わせ', root_path, class: "main-footer__anouncement__link"

  .main-footer__policy
    = link_to 'プライバシーポリシー', root_path, class: "main-footer__policy__link--first"
    = link_to '利用規約', root_path, class: "main-footer__policy__link"
    = link_to 'このサイトは個人のポートフォリオサイトです', root_path, class: "main-footer__policy__link"
    
  .main-footer__copyright
    %p Badsuru 

app/views/shared/_group_form.html.haml
.user-reg-main
  .user-reg-main__form  
    = form_for @group, builder: WithErrorFormBuilder do |f|
      .field-img
        .field-img__box
          = image_tag @group.group_avatar.url, size: "180x180", alt: "グループ画像", id: "my-group-img", alt: 'グループ画像', class: 'field-img__box__file'
          = f.label :group_avatar, class: 'label-reg-group' do
            = icon('fas', 'image', class: 'field-img__box__photo-icon')
            = f.file_field :group_avatar , class: "image-input-space--hidden"
      .field--1
        = f.label "グループ名", class: 'label-reg-group--1'
        %br/
        = f.text_field :name, autofocus:true, autocomplete: "name", placeholder: "グループ名", class: "text-space"
      .field
        = f.label "詳細", class: 'label-reg-group'
        %br/
        = f.text_area :detail, autofocus:true, autocomplete: "detail", placeholder: "チームの紹介", class: "text-space"
      .field
        = f.label "メンバー選択", class: 'label-reg-group'
        %br/
        = f.collection_check_boxes :user_ids, User.all, :id, :nickname

      .actions-reg
        = f.submit "登録する", class: "actions-reg__btn"

app/views/shared/_header.html.haml
%header.header
  .header-content
    .header-content__logo
      = link_to image_tag('/images/icon.png', class:"header-content__logo__img"), root_path

    - if user_signed_in?
      %li.header-content__linkItem
        %ul.header-content__linkItem__login
          = link_to "ログアウト", destroy_user_session_path, method: :delete
        %ul.header-content__linkItem__reg
          = link_to "プロフィール", edit_user_registration_path
    - else
      %li.header-content__linkItem
        %ul.header-content__linkItem__login
          = link_to "ログイン", new_user_session_path
        %ul.header-content__linkItem__reg
          = link_to "新規登録", new_user_registration_path

  -# %nav.global-nav
  -#   %ul.global-nav__list
  -#     %li.global-nav__item
  -#       メニュー1
  -#     %li.global-nav__item
  -#       メニュー2
  -#     %li.global-nav__item
  -#       メニュー3
  -#     %li.global-nav__item
  -#       メニュー4
  -#     %li.global-nav__item
  -#       メニュー5

  .hamburger#js-hamburger
    %span.hamburger__line.hamburger__line--1
    %span.hamburger__line.hamburger__line--2
    %span.hamburger__line.hamburger__line--3
  
  .black-bg#js-black-bg

app/views/shared/_image_form.html.haml
.field__img
  = f.label "グループ画像(任意)", class: 'label-reg-group'
    - if @group.group_avatar.present?
      .field__img--prev
        = image_tag group.group_avatar.url, id: "my-group-img", alt: 'グループ画像', class: 'my-group-img'
    - else
      .field__img--reg
        = icon('fas', 'image', class: 'photo-icon')
        = f.file_field :group_avatar , class: "image-input-space"

app/views/shared/_main.html.haml
= render "layouts/notification"

.main-visual
  = image_tag '/images/visual-bg.jpg', alt: '画像背景', height: '522px', width: '100%', class: 'main-visual__img--bg'
  .main-visual__images
    = image_tag '/images/visual-1.jpg', id: "main-visual__images-js", alt: '画像背景', class: 'main-visual__img--main'

.main-body
  .main-body__items
    = icon('fab', 'bitbucket', class: 'main-body__items__icon')
    %h1.main-body__title マイグループ
    = link_to "作成する" , new_group_path, class: "main-body__items__link"
  .my-group
    - if user_signed_in? 
      .my-group__items
        - @my_groups.each do |group|
          .my-group__item
            .my-group__item__img
              = image_tag group.group_avatar.url, id: "my-group-img", alt: 'グループ画像', class: 'my-group-img'
            %h1.my-group__item__title 
            = group.name
            %ul.my-group__item__infolist
              %li= "人数:#{group.users.count}"
              %li= "詳細:#{group.detail}"
              %li 活動拠点(詳細)
              %li= link_to "編集する", edit_group_path(group)
    - else
      %p.my-group__items--notuser-text ログイン (新規登録)してグループに参加しよう！！
      .my-group__items--notuser
        - @groups.each do |group|
          .my-group__item
            .my-group__item__img
              = image_tag group.group_avatar.url, id: "my-group-img", alt: 'グループ画像', class: 'my-group-img'
            %h1.my-group__item__title 
            = group.name
            %ul.my-group__item__infolist
              %li= "人数:#{group.users.count}"
              %li= "詳細:#{group.detail}"
              %li 活動拠点(詳細)


  .main-body__items
    = icon('fab', 'bitbucket', class: 'main-body__items__icon')
    %h1.main-body__title 参加予定の練習
    = link_to "作成する" , '', class: "main-body__items__link"

  .latest-practice__items
    %article.latest-practice
      .latest-practice__item
        .latest-practice__item__img 
          = image_tag '', id: "practice-image", alt: '練習画像', class: 'practice-img'
        .latest-practice__item__status
          %p 募集中
          %p.second 空きあり
        .latest-practice__item__title
          %p バドミントン同好会
        %ul.latest-practice__item__infolist
          %li 開催日：2020年8月8日
          %li 場所：総合体育館

    %article.latest-practice
      .latest-practice__item
        .latest-practice__item__img
          = image_tag '', id: "practice-image", alt: '練習画像', class: 'practice-img'
        .latest-practice__item__status
          %p 募集中
          %p.second 空きあり
        .latest-practice__item__title
          %p バドミントン同好会
        %ul.latest-practice__item__infolist
          %li 開催日：2020年8月8日
          %li 場所：総合体育館

  .main-body__items
    = icon('fab', 'bitbucket', class: 'main-body__items__icon')
    %h1.main-body__title 募集中の練習
    = link_to "作成する" , '', class: "main-body__items__link"

  .latest-practice__items
    %article.latest-practice
      .latest-practice__item
        .latest-practice__item__img 
          = image_tag '', id: "practice-image", alt: '練習画像', class: 'practice-img'
        .latest-practice__item__status
          %p 募集中
          %p.second 空きあり
        .latest-practice__item__title
          %p バドミントン同好会
        %ul.latest-practice__item__infolist
          %li 開催日：2020年8月8日
          %li 場所：総合体育館

    %article.latest-practice
      .latest-practice__item
        .latest-practice__item__img
          = image_tag '', id: "practice-image", alt: '練習画像', class: 'practice-img'
        .latest-practice__item__status
          %p 募集中
          %p.second 空きあり
        .latest-practice__item__title
          %p バドミントン同好会
        %ul.latest-practice__item__infolist
          %li 開催日：2020年8月8日
          %li 場所：総合体育館

app/views/shared/_nav.html.haml
.relative-nav
  %nav.nav-main
    %ul.nav-main__list
      %li.nav-main__list__item1
        = link_to "練習を作成する", new_practice_path
      %li.nav-main__list__item2
        = link_to "グループを作成する", new_group_path
      %li.nav-main__list__item3
        = link_to "メニュー", ""
      %li.nav-main__list__item4
        = link_to "メニュー", ""
      %li.nav-main__list__item5
        = link_to "メニュー", ""

app/views/shared/_practice_form.html.haml
.user-reg-main
  .user-reg-main__form  
    = form_for @practice,@group, builder: WithErrorFormBuilder do |f|
      -# .field-img
      -#   .field-img__box
      -#     = image_tag @practice.pracitc_avatar.url, size: "180x180", alt: "グループ画像", id: "my-group-img", alt: 'グループ画像', class: 'field-img__box__file'
      -#     = f.label :practice_avatar, class: 'label-reg-group' do
      -#       = icon('fas', 'image', class: 'field-img__box__photo-icon')
      -#       = f.file_field :practice_avatar , class: "image-input-space--hidden"
      .field--1
        = f.label "練習名", class: 'label-reg-practice--1'
        %br/
        = f.text_field :name, autofocus:true, autocomplete: "name", placeholder: "練習名", class: "text-space"
      .field
        = f.label "グループ名", class: 'label-reg-group'
        %br/
        = f.text_field :group_name, value: "", autocomplete: "group_name", placeholder: "グループ名", class: "text-space"
      .field
        = f.label "メンバー選択", class: 'label-reg-group'
        %br/
        = f.collection_check_boxes :user_ids, User.all, :id, :nickname
      .field
        = f.label "作成者名", class: 'label-reg-manager'
        %br/
        = f.text_field :manager, value: @practice.user.nickname, autocomplete: "manager", placeholder: "作成者名", class: "text-space"
      .field
        = f.label "練習日", class: 'label-reg-date'
        %br/
        = f.date_select(:date, use_month_numbers: true, prompt: "--", start_year: (Time.now.year), end_year: (Time.now.year + 5), default: Time.now(), class: "selectbox-space")
      .field
        = f.label "開始時間", class: 'label-reg-start_time'
        %br/
        = f.time_select :start_time, prompt: "--", class: "selectbox-space"
      .field
        = f.label "終了時間", class: 'label-reg-end_time'
        %br/
        = f.time_select :end_time, prompt: "--", class: "selectbox-space"
      .field
        = f.label "都道府県"
        %span.form-require 必須
        %br/
        = f.collection_select :prefecture_code, Prefecture.all, :id, :name, prompt: "--", value: '選択してください'
      .field
        = f.label "市区町村"
        %span.form-require 必須
        %br/
        = f.text_field :city, autofocus:true, autocomplete: "city", placeholder: "市区町村名",class: "text-space"
      .field
        = f.label "場所"
        %span.form-require 必須
        %br/
        = f.text_field :city, autofocus:true, autocomplete: "place", placeholder: "体育館名など",class: "text-space"
      .field
        = f.label "詳細"
        %span.form-require 必須
        %br/
        = f.text_area :detail, autofocus:true, autocomplete: "detail", placeholder: "詳細を入力",class: "text-space--detail"
      .field
        = f.label "ビジター代"
        %span.form-require 必須
        %br/
        = f.text_field :visitor_pay, autofocus:true, autocomplete: "visitor_pay", placeholder: "ビジター代",class: "text-space"
      .field
        = f.label "人数制限"
        %span.form-require 必須
        %br/
        = f.text_field :member_limit, autofocus:true, autocomplete: "member_limit", placeholder: "人数制限",class: "text-space"
        -# .field
        -# = f.label "シャトル持ち込み"
        -# %span.form-require 必須
        -# %br/
        -# = f.text_field :visitor_pay, autofocus:true, autocomplete: "visitor_pay", placeholder: "ビジター代",class: "text-space"

      .actions-reg
        = f.submit "登録する", class: "actions-reg__btn"